Базовая стилизация всех страниц
htmlacademy-htmlcss/1953987-sedona-33 pull request #5
Opened 2022-02-01 14:57 UTC by MarinaDobrusina

…ие изображений

---
:mortar_board: [Базовая стилизация всех страниц](https://up.htmlacademy.ru/htmlcss/33/user/1953987/tasks/6)

:boom: https://htmlacademy-htmlcss.github.io/1953987-sedona-33/5/

2022-02-02 08:52 UTC, CCher requested changes
переделайте правильно структуру  тегов `<ul>` и `<ol>` там, где указал и ниже на странице. 
Они должны содержать элементы <li>, а все остальные теги должны быть внутри ли-шек

2022-02-02 08:52 UTC, CCher commented on catalog.html
> +      <section class="hotel-catalog">
не нашёл закрывающего тега `</section>`

2022-02-02 08:52 UTC, CCher commented on catalog.html
>      </section>
если это тот самый закрывающий тег, то он явно не на месте

2022-02-02 08:52 UTC, CCher commented on index.html
>          <li class="advantages-item">
не закрыт тег `<li>`

2022-02-02 08:52 UTC, CCher commented on index.html
> +            <div class="advantages-light-blue">
`div ` не может быть дочерним элементом `ul`

2022-02-02 08:52 UTC, CCher commented on index.html
> +            <div class="advantages-light-blue">
то же самое

2022-02-02 09:03 UTC, MarinaDobrusina commented on index.html
>          <li class="advantages-item">
он вроде закрыт на 94-й строке

2022-02-03 08:31 UTC, CCher approved these changes
Технически всё верно. На мой взгляд не хватает семантики - в каталоге можно дома обернуть в `section`, пагинацию в свой секшн - поисковикам будет легче описать ваш сайт.

2022-02-03 08:31 UTC, merged