Добавляет сетку страниц и крупных блоков на флексах
htmlacademy-htmlcss/1953987-sedona-33 pull request #6
Opened 2022-02-05 12:17 UTC by MarinaDobrusina

2022-02-06 08:11 UTC, CCher requested changes
не нашёл на странице гостиницы разметки фильтра по стоимости. Он должен присутствовать, так как есть в макете (даже если не понятен механизм его работы)

2022-02-06 08:11 UTC, CCher commented on index.html
> +
Практичнее выделить первую бекграунд-картинку с надписями в отдельную секцию ( и на неё повесить бекграунд, а не на весь контейнер контента). Обычно на сайтах на первом месте идёт призывный баннер, рекламный баннер, слайдер... т.е. это место может меняться в зависимости от потребностей клиента и лучше его выделять в отдельную секцию, чтобы легко было менять содержимое, не затрагивая всю страницу. Это первое, а второе - как Вы планируете сверху ставить резной край из макета, если есть один только имидж?

2022-02-06 08:11 UTC, CCher commented on index.html
> +              <li class="advantages-item advantages-real-town">
Не технологично для работы делать одинаковые блоки на одной странице разными способами. У Вас хороший первый вариант `advantages-item`, просто сдублируйте его во вторую лишку и добавьте изменения через классы и будет замечательно!

2022-02-06 08:11 UTC, CCher commented on catalog.html
>      <header class="inner-header">
второй хедер на странице не вызовет путанницы? Может лучше просто `<section class="inner-header">`?

2022-02-06 12:42 UTC, MarinaDobrusina commented on index.html
> +              <li class="advantages-item advantages-real-town">
Константин, я не поняла этот пункт(

2022-02-06 12:43 UTC, MarinaDobrusina commented on catalog.html
>      <header class="inner-header">
про второй хедер я с вами согласна, но так делали в примере на лайве, поэтому сделала также. Стоит переделать?

2022-02-07 05:06 UTC, CCher commented on catalog.html
>      <header class="inner-header">
оставляйте так, как учили на лекции.

2022-02-07 15:16 UTC, CCher approved these changes

2022-02-07 15:16 UTC, merged